# golangci-lint config
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.25"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    - deadcode
    - varcheck
    - structcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: vulnlabz
  govet:
    enable:
      - shadow
    disable:
      - fieldalignment

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 3
